# This file is a configuration template for the initial values on each calibration run

[general]
target_node = "readout_amplitude_two_state_optimization"
qubits = ["q06", "q07", "q08", "q09", "q10"]
couplers = ["q06_q07"]

#   --------------
#   Node reference
#   --------------
#
#   punchout
#   resonator_spectroscopy
#   qubit_01_spectroscopy
#   qubit_01_spectroscopy_pulsed
#   qubit_01_cw_spectroscopy
#   rabi_oscillations
#   ramsey_correction
#   resonator_spectroscopy_1
#   qubit_12_spectroscopy_pulsed
#   qubit_12_spectroscopy_multidim
#   rabi_oscillations_12
#   ramsey_correction_12
#   resonator_spectroscopy_2
#   ro_frequency_two_state_optimization
#   ro_frequency_three_state_optimization
#   ro_amplitude_two_state_optimization
#   ro_amplitude_three_state_optimization
#   coupler_spectroscopy
#   coupler_resonator_spectroscopy
#   motzoi_parameter
#   n_rabi_oscillations
#   randomized_benchmarking
#   state_discrimination
#   T1
#   T2
#   T2_echo
#   randomized_benchmarking
#   all_XY
#   check_cliffords
#   cz_chevron
#   cz_chevron_test
#   cz_chevron_amplitude
#   cz_optimize_chevron
#   reset_chevron
#   reset_calibration_ssro
#   cz_calibration
#   cz_calibration_ssro
#   cz_dynamic_phase
#   cz_dynamic_phase_swap
#   process_tomography_ssro
#   tqg_randomized_benchmarking
#   tqg_randomized_benchmarking_interleaved
