# This file is a configuration template for the initial values on each calibration run

target_node = "ro_amplitude_two_state_optimization"
qubits = ["q06", "q07", "q08", "q09", "q10"]
couplers = ["q06_q07"]
cooldown = "13/05/2025"
name = "no_name_for_this_run_set"
is_internal = true
runner_logo = "resources/runner_logo.png"

#   --------------
#   Node reference
#   --------------
#
#   punchout
#   resonator_spectroscopy
#   qubit_01_spectroscopy
#   rabi_oscillations
#   ramsey_correction
#   resonator_spectroscopy_1
#   qubit_12_spectroscopy
#   rabi_oscillations_12
#   ramsey_correction_12
#   resonator_spectroscopy_2
#   ro_frequency_two_state_optimization
#   ro_frequency_three_state_optimization
#   ro_amplitude_two_state_optimization
#   ro_amplitude_three_state_optimization
#   resonator_spectroscopy_vs_current
#   qubit_spectroscopy_vs_current
#   T1
#   T2
#   T2_echo
#   randomized_benchmarking_ssro
#   all_XY
#   check_cliffords
#   cz_chevron
#   cz_chevron_test
#   cz_chevron_amplitude
#   cz_optimize_chevron
#   reset_chevron
#   reset_calibration_ssro
#   cz_calibration
#   cz_calibration_ssro
#   cz_dynamic_phase
#   cz_dynamic_phase_swap
#   process_tomography_ssro
#   tqg_randomized_benchmarking
#   tqg_randomized_benchmarking_interleaved
