# This code is part of Tergite
#
# (C) Copyright Eleftherios Moschandreou 2024
# (C) Copyright Liangyu Chen 2024
# (C) Copyright Stefan Hill 2024
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.


# -------------------
# SPI A configuration
# -------------------

[q11_q12]
spi_module_number = 1
dac_name = "dac0"
edge_group = 1

[q12_q13]
spi_module_number = 1
dac_name = "dac1"
edge_group = 2

[q13_q14]
spi_module_number = 1
dac_name = "dac2"
edge_group = 1

[q14_q15]
spi_module_number = 1
dac_name = "dac3"
edge_group = 2

[q08_q09]
spi_module_number = 2
dac_name = "dac0"

[q12_q17]
spi_module_number = 2
dac_name = "dac1"
edge_group = 4

[q07_q12]
spi_module_number = 2
dac_name = "dac2"

[q08_q13]
spi_module_number = 2
dac_name = "dac3"

[q09_q14]
spi_module_number = 4
dac_name = "dac0"

[q06_q07]
spi_module_number = 4
dac_name = "dac1"

[q09_q10]
spi_module_number = 4
dac_name = "dac2"

[q11_q16]
spi_module_number = 4
dac_name = "dac3"
edge_group = 3

[q07_q08]
spi_module_number = 6
dac_name = "dac0"

[q10_q15]
spi_module_number = 6
dac_name = "dac1"

[q06_q11]
spi_module_number = 6
dac_name = "dac2"


# -------------------
# SPI B configuration
# -------------------

[q16_q17]
spi_module_number = 10
dac_name = "dac0"
edge_group = 2

[q17_q18]
spi_module_number = 10
dac_name = "dac1"
edge_group = 1

[q18_q19]
spi_module_number = 10
dac_name = "dac2"
edge_group = 2

[q19_q20]
spi_module_number = 10
dac_name = "dac3"
edge_group = 1

[q18_q23]
spi_module_number = 5
dac_name = "dac0"
edge_group = 4

[q17_q22]
spi_module_number = 5
dac_name = "dac1"
edge_group = 3

[q16_q21]
spi_module_number = 5
dac_name = "dac2"
edge_group = 4

[q19_q24]
spi_module_number = 5
dac_name = "dac3"
edge_group = 3

[q20_q25]
spi_module_number = 8
dac_name = "dac0"
edge_group = 4

[q21_q22]
spi_module_number = 8
dac_name = "dac1"
edge_group = 1

[q22_q23]
spi_module_number = 8
dac_name = "dac2"
edge_group = 2

[q23_q24]
spi_module_number = 8
dac_name = "dac3"
edge_group = 1

[q24_q25]
spi_module_number = 7
dac_name = "dac0"
edge_group = 2

[q13_q18]
spi_module_number = 7
dac_name = "dac1"
edge_group = 3

[q15_q20]
spi_module_number = 7
dac_name = "dac2"
edge_group = 3

[q14_q19]
spi_module_number = 7
dac_name = "dac3"
edge_group = 4
